
export const LOGOS_NAME_MAP = {
    'nba': {
        'Atlanta Hawks': 'ATL',
        'Brooklyn Nets': 'BKN',
        'Boston Celtics': 'BOS',
        'Charlotte Hornets': 'CHA',
        'Chicago Bulls': 'CHI',
        'Cleveland Cavaliers': 'CLE',
        'Dallas Mavericks': 'DAL',
        'Denver Nuggets': 'DEN',
        'Detroit Pistons': 'DET',
        'Golden State Warriors': 'GS',
        'Houston Rockets': 'HOU',
        'Indiana Pacers': 'IND',
        'Los Angeles Clippers': 'LAC',
        'Los Angeles Lakers': 'LAL',
        'Memphis Grizzlies': 'MEM',
        'Miami Heat': 'MIA',
        'Milwaukee Bucks': 'MIL',
        'Minnesota Timberwolves': 'MIN',
        'New Orleans Pelicans': 'NO',
        'New York Knicks': 'NY',
        'Oklahoma City Thunder': 'OKC',
        'Orlando Magic': 'ORL',
        'Philadelphia 76ers': 'PHI',
        'Phoenix Suns': 'PHX',
        'Portland Trail Blazers': 'POR',
        'San Antonio Spurs': 'SA',
        'Sacramento Kings': 'SAC',
        'Toronto Raptors': 'TOR',
        'Utah Jazz': 'UTAH',
        'Washington Wizards': 'WSH'
    },
    'epl': {
        'Arsenal': 'ars',
        'Aston Villa': 'avl',
        'Brighton': 'bha',
        'Brentford': 'bre',
        'Burnley': 'bur',
        'Chelsea': 'che',
        'Crystal Palace': 'cp',
        'Everton': 'eve',
        'Leeds United': 'lee',
        'Leicester': 'lei',
        'Liverpool': 'liv',
        'Manchester City': 'mci',
        'Manchester Utd': 'mu',
        'Newcastle Utd': 'new',
        'Norwich City': 'nor',
        'Southampton': 'sou',
        'Tottenham': 'tot',
        'Watford': 'wat',
        'West Ham': 'whu',
        'Wolve': 'wol'
    }
}